behaviors:
  AI:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 512
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 1
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 100000
    max_steps: 100000
    time_horizon: 16
    summary_freq: 5000
    threaded: false
    self_play: null
    behavioral_cloning: null